### ISSUE TITLE
Name and icon

### ISSUE THREAD

**Issue by bragefuglseth** [pojntfx/multiplex#1]
The app would benefit from a name and an icon following GNOME's guidelines.

According to the [naming guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html) a good app name should avoid made-up combinations. Since the current app name, Vintangle, has this, I think we should try to find a new one. This is easiest to do before the app is published anywhere, since it lets us change the app ID as well without having to jump through any hoops.

I suggest to call the app Multiplex. A multiplex is a movie theater building with multiple screens, which fits the app nicely as a metaphor.

I can design an icon for the app that fits the name and follows GNOME's [app icon guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html). Let me know what you think! :)

**Comment by pojntfx** [comment]
Absolutely, this sounds great! I really like the metaphor. I've just renamed the repo, IDs, file names etc. accordingly. I'd really appreciate this app having a logo that follows the GNOME guidelines - would you be able to give a rough ETA on this so I can plan a release? ^^

**Comment by bragefuglseth** [comment]
I think I'll be able to finish it this week 👍

**Comment by pojntfx** [comment]
Thanks, that would be awesome!

**Comment by bragefuglseth** [comment]
Here's the current iteration of the icon:

![Preview](https://github.com/pojntfx/multiplex/assets/91388039/5250c300-1438-4df8-9aa5-2872c593c855)

**Comment by bragefuglseth** [comment]
I tried to implement the icon, but I couldn't build the project in GNOME Builder, so here are the SVG files! You should put all of them where the current app icons are. The icon is scalable, and replaces all the current PNG variants. You'll need to make changes to the build process to implement the icon. I'd be grateful if you credited me in the artists section of the about window :)

![com pojtinger felicitas Multiplex Source](https://github.com/pojntfx/multiplex/assets/91388039/04f5d5ef-01f7-4067-b52d-784f6f8e5754)
![com pojtinger felicitas Multiplex](https://github.com/pojntfx/multiplex/assets/91388039/cbb34e30-9d6a-45bf-8ce9-fecc41899203)
![com pojtinger felicitas Multiplex Devel](https://github.com/pojntfx/multiplex/assets/91388039/25a61989-2b5c-483b-97a9-28aa87fcb7cb)
![com pojtinger felicitas Multiplex-symbolic](https://github.com/pojntfx/multiplex/assets/91388039/9b459190-4756-46c3-b9d9-4e5b5ef4caf2)

**Comment by pojntfx** [comment]
Thanks a lot, I really appreciate it and really like the new icon! I'll be sure to integrate them ASAP & credit you accordingly ^^

**Comment by pojntfx** [comment]
![Screenshot of the credits section](https://github.com/pojntfx/multiplex/assets/28832235/bb6affcc-e672-4ebd-a8c6-184ab0435acb)

Should be all ready now; I've added attribution to the usual places in the README and about window. Thanks again!
