### ISSUE TITLE
Make app buildable out-of-the-box in GNOME Builder

### ISSUE THREAD

**Issue by bragefuglseth** [pojntfx/multiplex#2]
While working on the app icon, I noticed that the app depends on Go being installed on the host system to build in GNOME Builder. Is it possible to take advantage of Flatpak to make the app run with just the Go SDK extension instead? I know this is possible with Rust and C.

**Comment by pojntfx** [comment]
Hmmm, this is strange! There is a valid Flatpak definition already, and I'm building it in CI too so it should work: https://github.com/pojntfx/multiplex/blob/main/com.pojtinger.felicitas.Multiplex.yaml

I just tried in in GNOME builder, for some reason it didn't build the first time (what you mentioned - Go on the host system etc.), then I converted the manifest to JSON which worked, then back to YAML and it still built. I'll try to investigate.

**Comment by pojntfx** [comment]
Looks like we're running into https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/520. I'll convert it to JSON :)

**Comment by pojntfx** [comment]
See: 93ce502b4c1374814ff23d11dc65179c38c12b15

I'll try and do a clean (re-)build of this with Builder in GNOME OS to validate that everything works, but at least my local Fedora installation works fine!

**Comment by pojntfx** [comment]
Alright, looks like its all working now:

![Screenshot from 2023-09-03 17-24-08](https://github.com/pojntfx/multiplex/assets/28832235/e4268efb-7d83-40fa-bdd4-146baf597723)

![Screenshot from 2023-09-03 17-28-52](https://github.com/pojntfx/multiplex/assets/28832235/0a0cd930-c194-4795-b80b-cb8f9a4ba33b)

Feel free to reopen if it doesn't work on your system! ^^
