### ISSUE TITLE
Better appadata summary

### ISSUE THREAD

**Issue by bertob** [pojntfx/multiplex#4]
The current summary "Synchronized torrent streaming for distributed watch parties" is a bit long, and goes into too much detail.

I'd try something like "Watch torrents with your friends", or maybe just "Watch videos with your friends".

For reference, these are the appdata summary guidelines: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata#summary

**Comment by pojntfx** [comment]
Yup, that's a really good point. Its def. too technical - I'll take a look ASAP!

**Comment by pojntfx** [comment]
Should be released to Flathub any second now: https://github.com/flathub/com.pojtinger.felicitas.Multiplex/pull/1
